
# Script:       pyproject.toml
# Description:  auto_forge package configuration

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "auto_forge"
version = "0.0.1"
description = "AutoForge: You companion Bob the Builder"
readme = "README.md"
authors = [{name = "Intel AutoForge team", email = "imcv2_team@intel.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.9"  # AutoPilot requires Python 3.9 or later
dependencies = [
    "colorama",
    "tabulate",
    "psutil",
    "toml",
    "gitpython",
    "jsonpath-ng",
    "json5",
    "jsonschema",
    "pyaml",
    "ruamel.yaml",
    "cmd2"
]

[project.urls]
homepage = "https://github.com/intel-innersource/firmware.ethernet.imcv2"
repository = "https://github.com/intel-innersource/firmware.ethernet.imcv2/tree/main/scripts/auto_forge"

[project.scripts]
autopilot = "auto_forge.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "auto_forge",
    "auto_forge.core",
    "auto_forge.commands",
]

# Extended package properties should only be placed here to ensure compliance with PEP 621.
[tool.autopilot_metadata]
fancy_name = "AutoForge"
