# Script:       pyproject.toml
# Description:  auto_forge package configuration

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "auto_forge"
version = "1.1.1"
description = "AutoForge: YABS (yet another build system tool)"
readme = "README.md"
authors = [{ name = "AutoForge team", email = "team@auto_forge.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.9"  # Requires Python 3.9 or later
dependencies = [
    "wheel",
    "colorama",
    "rich",
    "tabulate",
    "psutil",
    "toml",
    "gitpython",
    "jsonpath-ng",
    "json5",
    "jsonschema",
    "pyaml",
    "ruamel.yaml",
    "GitPython",
    "prompt_toolkit",
    "cmd2"
]

[project.urls]
homepage = "https://github.com/emichael72/auto_forge.git"
repository = "https://github.com/emichael72/auto_forge.git"

[project.scripts]
autoforge = "auto_forge.__main__:main"

[tool.setuptools]
platforms = ["linux"]
package-dir = { "" = "src" }
packages = [
    "auto_forge",
    "auto_forge.core",
    "auto_forge.common",
    "auto_forge.commands",
]

# Extended package properties should only be placed here to ensure compliance with PEP 621.
[tool.autoforge_metadata]
fancy_name = "AutoForge"
